============================= test session starts ==============================
platform darwin -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0 -- /opt/homebrew/opt/python@3.10/bin/python3.10
cachedir: .pytest_cache
rootdir: /Users/nico/code/sathustra/data-model-lifecycle/tests, configfile: pytest_kitt.ini
plugins: anyio-3.6.2
collecting ... collected 10 items

tests/lifecycle/test_mlflow.py::TestMlflow::test_model_target_is_mlflow PASSED [ 10%]
tests/lifecycle/test_mlflow.py::TestMlflow::test_mlflow_experiment_is_not_null PASSED [ 20%]
tests/lifecycle/test_mlflow.py::TestMlflow::test_mlflow_model_name_is_not_null PASSED [ 30%]
tests/lifecycle/test_mlflow.py::TestMlflow::test_mlflow_experiment_exists PASSED [ 40%]
tests/lifecycle/test_mlflow.py::TestMlflow::test_mlflow_model_exists PASSED [ 50%]
tests/lifecycle/test_mlflow.py::TestMlflow::test_mlflow_model_in_production PASSED [ 60%]
tests/lifecycle/test_prefect.py::TestPrefect::test_prefect_flow_name_is_not_null PASSED [ 70%]
tests/lifecycle/test_prefect.py::TestPrefect::test_prefect_log_level_is_warning PASSED [ 80%]
tests/lifecycle/test_prefect.py::TestPrefect::test_prefect_tasks FAILED  [ 90%]
tests/lifecycle/test_prefect.py::TestPrefect::test_prefect_flow PASSED   [100%]

=================================== FAILURES ===================================
________________________ TestPrefect.test_prefect_tasks ________________________

self = <tests.lifecycle.test_prefect.TestPrefect object at 0x179cb8250>

    def test_prefect_tasks(self):
        """
        verify that the all the prefect tasks are created
        """
        assert preprocess_new_data.name == 'preprocess_new_data', "preprocess_new_data task is not defined"
        assert evaluate_production_model.name == 'evaluate_production_model', "evaluate_production_model task is not defined"
        assert re_train.name == 're_train', "re_train task is not defined"
        assert transition_model.name == 'transition_model', "transition_model task is not defined"
>       assert notify.name == 'notify', "notify task is not defined"
E       NameError: name 'notify' is not defined

tests/lifecycle/test_prefect.py:34: NameError
=========================== short test summary info ============================
FAILED tests/lifecycle/test_prefect.py::TestPrefect::test_prefect_tasks - Nam...
================== 1 failed, 9 passed, 100 warnings in 5.96s ===================
